import fs from 'node:fs'
Object.defineProperty(process,'platform',{value:'linux'})
process.env.PLAYWRIGHT_BROWSERS_PATH='/data/data/com.termux/files/home/.cache/ms-playwright'
const {chromium}=await import('@playwright/test')
const browser=await chromium.launch({executablePath:'/data/data/com.termux/files/usr/lib/chromium/chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']})
const ctx=await browser.newContext({viewport:{width:412,height:915},acceptDownloads:true})
await ctx.addInitScript(()=>{sessionStorage.setItem('venice-auth','audit-fixture-key-not-a-real-credential')})
const png='iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAAHIElEQVR4nO3VMQ0AMAzAsEIZtEEcxMHoEUsGkC9z7gMgaNYLAFhhAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABBlAABRBgAQZQAAUQYAEGUAAFEGABD1ATMUR0GURu9wAAAAAElFTkSuQmCC'
const requests=[],errors=[],checks=[]
await ctx.route('https://api.venice.ai/api/v1/**',async route=>{
 const req=route.request(),u=new URL(req.url());let response={}
 if(u.pathname.endsWith('/api_keys/rate_limits'))response={data:{accessPermitted:true,balances:{USD:10,DIEM:0}}}
 else  if(u.pathname.endsWith('/models')){const type=u.searchParams.get('type');response={data:(type==='text'?['venice-uncensored-1-2']:type==='image'?['lustify-v8','krea-2-turbo']:type==='inpaint'?['qwen-edit-uncensored']:[]).map(id=>({id,type,model_spec:{name:id,offline:false,capabilities:{supportsFunctionCalling:false},constraints:{promptCharacterLimit:1500}}}))}}
 else if(u.pathname.endsWith('/chat/completions'))response={choices:[{message:{role:'assistant',content:JSON.stringify({say:'AUDIT_READY',patches:[]})}}]}
 else if(u.pathname.endsWith('/image/generate')){requests.push({path:u.pathname,body:req.postDataJSON()});response={id:'audit-image',images:[png],timing:{inference:1},request:{model:'lustify-v8'}}}
 else if(u.pathname.endsWith('/image/multi-edit')||u.pathname.endsWith('/image/edit')||u.pathname.endsWith('/image/upscale')||u.pathname.endsWith('/image/background-remove')){requests.push({path:u.pathname,hasBody:!!req.postData()});return route.fulfill({status:200,contentType:'image/png',body:Buffer.from(png,'base64')})}
 else if(u.pathname.endsWith('/image/styles'))response={data:[]}
 await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(response)})
})
const page=await ctx.newPage();page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message))
const check=async(name,fn)=>{try{const evidence=await fn();checks.push({name,status:'PASS',evidence})}catch(e){checks.push({name,status:'FAIL',evidence:e.message.slice(0,500)})}console.log(name,checks.at(-1).status)}
await page.goto('http://127.0.0.1:5174',{waitUntil:'networkidle'})
await check('Chat submit with controlled API response',async()=>{await page.getByRole('textbox',{name:'Message Noor',exact:true}).fill('Reply with READY');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('AUDIT_READY',{exact:false}).first().waitFor();return 'Response rendered'})
await check('Image tab, prompt and Generate',async()=>{await page.getByRole('tab',{name:'Image',exact:true}).click();await page.getByPlaceholder('Describe the image you want to create…').fill('A blue ceramic mug on a desk');await page.getByRole('button',{name:/^Generate/}).last().click();await page.waitForTimeout(800);if(!await page.locator('img').count())throw Error('Generate returned no image; page errors: '+errors.join('; '));return {body:(await page.locator('body').innerText()).slice(-2200),images:await page.locator('img').count()}})
await check('Image result full viewer and download',async()=>{await page.getByRole('button',{name:'Open image full screen',exact:true}).last().click();const dialog=page.getByRole('dialog',{name:'Full image',exact:true});await dialog.waitFor();const download=page.waitForEvent('download',{timeout:6000}).catch(e=>({error:e.message}));await dialog.getByRole('button',{name:'Download',exact:true}).click();const d=await download;if(d.error)throw Error(d.error);await dialog.getByRole('button',{name:'Close',exact:true}).click();return {file:d.suggestedFilename()}})
await check('Tools modes',async()=>{await page.keyboard.press('Escape');let close=page.getByRole('button',{name:'Close',exact:true});if(await close.count())await close.last().click();await page.getByRole('tablist',{name:'Create mode'}).getByRole('tab',{name:'Tools',exact:true}).click();return {body:(await page.locator('body').innerText()).slice(-2500)}})
await check('Tools upload, edit and result',async()=>{await page.locator('input[type=file]').first().setInputFiles({name:'audit.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'Remove image',exact:true}).waitFor();return {preview:await page.locator('img').count(),remove:await page.getByRole('button',{name:'Remove image',exact:true}).count()}})

await check('Edit submit and returned image',async()=>{await page.getByPlaceholder('Keep identity. Change only what I type…').fill('Change the mug to green');await page.getByRole('button',{name:'Edit Image',exact:true}).click();await page.getByRole('button',{name:'Open image full screen',exact:true}).waitFor();return {request:requests.at(-1),resultVisible:true}})
await check('Tools full viewer and browser download',async()=>{await page.getByRole('button',{name:'Open image full screen',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Full image',exact:true});await dialog.waitFor();const wait=page.waitForEvent('download',{timeout:6000}).catch(e=>({error:e.message}));await dialog.getByRole('button',{name:'Download',exact:true}).click();const d=await wait;if(d.error)throw Error(d.error);await dialog.getByRole('button',{name:'Close',exact:true}).click();return {file:d.suggestedFilename()}})
await check('Upscale and background removal',async()=>{let results=[];for(const [tool,submit] of [['Upscale','Upscale Image'],['BG','Remove Background']]){await page.getByRole('button',{name:tool,exact:true}).click();await page.getByRole('button',{name:submit,exact:true}).click();await page.getByRole('button',{name:'Open image full screen',exact:true}).waitFor();results.push(requests.at(-1))}return results})
await check('Swap reference guards and dual mapping',async()=>{await page.getByRole('button',{name:'Swap',exact:true}).first().click();let disabled=await page.getByRole('button',{name:/^Swap face$/}).isDisabled();await page.getByRole('button',{name:'Dual-person off',exact:true}).click();return {missingReferenceBlocked:disabled,secondReferenceVisible:await page.getByText('Upload female face / head / body identity',{exact:true}).isVisible()}})
await check('Outfit screen guard',async()=>{await page.getByRole('button',{name:'Outfit',exact:true}).first().click();return (await page.locator('body').innerText()).slice(-1800)})
await check('Source remove control',async()=>{await page.getByRole('button',{name:'Remove image',exact:true}).click();return {removed:await page.getByRole('button',{name:'Remove image',exact:true}).count()===0}})

await check('Image tab survives reload',async()=>{await page.reload({waitUntil:'networkidle'});return {body:(await page.locator('body').innerText()).slice(-1200),images:await page.locator('img').count()}})
fs.writeFileSync('/data/data/com.termux/files/home/chilli-audit-fixture-complete-results.json',JSON.stringify({scope:'Controlled provider fixtures, not live inference or native media verification',checks,errors,requests},null,2));console.log(JSON.stringify({checks,errors,requests},null,2));await browser.close()
